# An example how you can use docker from within the singularity container
# torpedos all 'don't run as root' protection though.
# (remember, being allowed to run docker containers == root access)
[anysnake2]
url2 = "dev" # replace with fixed version outside of tests/examples


[nixpkgs]
# the nixpkgs used inside the container
packages = [ # use https://search.nixos.org/packages to search
	"fish",
	"docker-client",
]
url = "github:NixOS/nixpkgs/master/24.05"

[rust]
version="1.55.0"
url = "github:oxalica/rust-overlay/master/d720bf3cebac38c2426d77ee2e59943012854cb8"

[container.env]
ANYSNAKE2="1"

# container settings
[container.volumes_rw]
"." = "/project" # map the current folder to /project
"/var/run/docker.sock" = "/var/run/docker.sock"

[cmd.default]
run = """
cd /project
jupyter notebook
"""

[cmd.shell]
run = """fish
"""

[outside_nixpkgs]
url = "github:NixOS/nixpkgs/master/24.05"

[ancient_poetry]
url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=54a06abec3273f42f9d86a36f184dbb3089cd9c9"

[flake-util]
url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"
