# this will not work with the 2024 poetry2nix - poetry2nix is explicitly 
# only supporting the current release at any one point in time.
[anysnake2]
# We leverage nix flakes to run exactly that version.
url2 = "dev"

[nixpkgs]
packages = ['strace', 'python38']
url = "github:NixOS/nixpkgs/master/22.05"

[python] # python section is optional
version="3.10" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)
ecosystem_date="2022-11-23" # you get whatever packages the solver would have produced on that day

[python.packages]
# you can use version specifiers from https://www.python.org/dev/peps/pep-0440/#id53
rpy2="3.5.5" # starting with 3.5.6 it no longer compiles on 22.05
scipy=""


[R] # R section is optional
date="2022-05-10" # you get whatever packages were current that day.
packages = [
	"Rcpp",
	"stringi"

]
url = "github:TyberiusPrime/nixR/main/bbfed71d90b2967f2226dd1cdb11b9060a5bef24"

[outside_nixpkgs]
url = "github:NixOS/nixpkgs/master/22.11"

[ancient_poetry]
url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=54a06abec3273f42f9d86a36f184dbb3089cd9c9"

[poetry2nix]
url = "github:nix-community/poetry2nix/master/8c25e871bba3f472e1569bbf6c0f52dcc34bf2a4"

[flake-util]
url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"
