# Here we have github/mercurial python packages
# that get a hash auto-added on first use
# (example used for testing)
# package settings
[anysnake2]
	rev = "dev" # pre 2.0 - 2.0+ uses url2
	url = "github:TyberiusPrime/anysnake2_release_flakes" # pre 2.0 - 2.0+ uses url2
	url2 = "dev"


[nixpkgs]
# the nixpkgs used inside the container
	packages = ["which"]
	url = "github:NixOS/nixpkgs/master/24.05"


[python] # python section is optional
	ecosystem_date="2024-02-16" # you get whatever packages the solver would have produced on that day
	version="3.10" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)


[python.packages]
	dppd = { url = "git+https://github.com/tyberiusprime/dppd?ref=master&rev=e5fc8853289efa79ff278effd14f89e1c652b6b6", poetry2nix.buildInputs = ["setuptools"] }
# example for github and hg. See just_python_discover_newest_revision for git
	i3-instant-layout = { url = "github:TyberiusPrime/i3-instant-layout/master/bd5e592579c2d9a27cbe120bbf473f5d092a74d5", poetry2nix.buildInputs = ["setuptools"] }
	lvr = { url = "hg+https://hg.sr.ht/~bwe/lvr?rev=db6f0a3254fbd3939d6b6b8c6d1711e7129faba1", poetry2nix.buildInputs = ["setuptools"] }
	mizani = { version = "pypi:0.13.0" }


[dev_shell]
	inputs = []
	shell = "bash"


[outside_nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=54a06abec3273f42f9d86a36f184dbb3089cd9c9"


[poetry2nix]
	url = "github:nix-community/poetry2nix/master/8c25e871bba3f472e1569bbf6c0f52dcc34bf2a4"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"
