# Here we have github/mercurial python packages
# that get a hash auto-added on first use
# (example used for testing)
# package settings
[anysnake2]
	url2 = "dev"


[nixpkgs]
# the nixpkgs used inside the container
	packages = ["which"]
	url = "github:NixOS/nixpkgs/master/24.05"


[python] # python section is optional
	ecosystem_date="2024-02-16" # you get whatever packages the solver would have produced on that day
	version="3.10" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)


[python.packages]
	dppd = { url = "git+https://github.com/tyberiusprime/dppd", build_systems = ["setuptools"] }
	lvr = { url = "hg+https://hg.sr.ht/~bwe/lvr" , build_systems = ["setuptools"] }
	mizani = { version = "pypi" }
# example for github and hg. See just_python_discover_newest_revision for git
	i3-instant-layout = { url = "github:TyberiusPrime/i3-instant-layout", build_systems = ["setuptools"] }


[outside_nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"

