# Here we have github/mercurial python packages
# that get a hash auto-added on first use
# (example used for testing)
# package settings
[anysnake2]
	url2 = "dev"


[nixpkgs]
# the nixpkgs used inside the container
	packages = ["which"]
	url = "github:NixOS/nixpkgs/master/24.05"


[python] # python section is optional
	ecosystem_date="2024-02-16" # you get whatever packages the solver would have produced on that day
	version="3.10" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)


[python.packages]
	dppd = { url = "git+https://github.com/tyberiusprime/dppd", poetry2nix.buildInputs = ["setuptools"] }
	lvr = { url = "hg+https://hg.sr.ht/~bwe/lvr" , poetry2nix.buildInputs = ["setuptools"] }
	mizani = { version = "pypi" }
# example for github and hg. See just_python_discover_newest_revision for git
	i3-instant-layout = { url = "github:TyberiusPrime/i3-instant-layout", poetry2nix.buildInputs = ["setuptools"] }


[outside_nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=54a06abec3273f42f9d86a36f184dbb3089cd9c9"


[poetry2nix]
	url = "github:nix-community/poetry2nix/master/8c25e871bba3f472e1569bbf6c0f52dcc34bf2a4"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"
