# Here we have github/mercurial python packages
# that get a hash auto-added on first use
# (example used for testing)
# package settings
[anysnake2]
url2="dev"

[nixpkgs]
# the nixpkgs used inside the container
rev = "23.11" # the nixpgks version or github hash
packages = ["which"]
url = "github:NixOS/nixpkgs/master/24.05"


[python] # python section is optional
version="3.11" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)
ecosystem_date="2024-02-16" # you get whatever packages the solver would have produced on that day


[python.packages]
# for git / github
plotnine = { url = "git+https://github.com/has2k1/plotnine"}#
#, poetry2nix.buildInputs = ["setuptools", "setuptools-scm"] }
#lvr = { url = "hg+https://hg.sr.ht/~bwe/lvr?rev=db6f0a3254fbd3939d6b6b8c6d1711e7129faba1",  poetry2nix.buildInputs = ["setuptools"]}

# this plotnine needs a newer mizani than we have on 2022-02-16
# so we fetch the newest version from pypi
mizani = { version = "pypi" } # 'pypi' and 'pypi:' will both work
