# Here we have github/mercurial python packages
# that get a hash auto-added on first use
# (example used for testing)
# package settings
[anysnake2]
rev = "dev"

[outside_nixpkgs]
rev = "21.05" # the nixpgks version or github hash

[nixpkgs]
# the nixpkgs used inside the container
rev = "24.05" # the nixpgks version or github hash
packages = ["which"]


[python] # python section is optional
version="3.11" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)
ecosystem_date="2022-02-16" # you get whatever packages the solver would have produced on that day


[python.packages]
# see other examples for the regular syntax, this
# is just 'how to wrap nix-source-fetchers'
# for github
plotnine = { git= "https://github.com/has2k1/plotnine"}
# this plotnine needs a newer mizani than we have.
mizani = {pypi="0.8.1"}
# plotnine needs a newer statsmodels than the ecosystem date.
#statsmodels = { pypi = "0.14.0", "pypi_url_0.14.0" = "https://files.pythonhosted.org/packages/13/a3/a8bf1c9e6d0193f854d9a79cb86a65dac0866de64051ff96e35bc7ecedfe/statsmodels-0.14.0.tar.gz" }
#pandas = { pypi = "2.2.0", "pypi_url_2.2.0" = "https://files.pythonhosted.org/packages/03/d2/6fb05f20ee1b3961c7b283c1f8bafc6de752155d075c5db61c173de0de62/pandas-2.2.0.tar.gz" }
# # for mercurial
# lvr = {method = "fetchhg", url="https://hg.sr.ht/~bwe/lvr" , rev = "db6f0a3254fbd3939d6b6b8c6d1711e7129faba1", hash_db6f0a3254fbd3939d6b6b8c6d1711e7129faba1 = "sha256-r2yDQ4JuOAZ7oWfjat2R/5OcMi0q7BY1QCK/Z9hyeyY=" }
# pypipegraph2 = {method = "fetchFromGitHub", owner="TyberiusPrime", repo="pypipegraph2", rev = "5996cf9d027c797ac15d892877ce3e35a87443be", hash_5996cf9d027c797ac15d892877ce3e35a87443be = "sha256-JemWufQ/9PScTakg/zoMvDSxNvcojaHkzVsvNK6dawo=" }

##
# you can fetch from github, git and mercurial (any nix fetcher actually, see
# https://nixos.org/manual/nixpkgs/stable/#chap-pkgs-fetchers)
# if using fetchFromGitHub or fetchhg, the necessary hash will be added to this file
# on a trust-on-first-use-basis


