# fully featured anysnake2.toml example
[anysnake2]
# We leverage nix flakes to run exactly that version.
	rev = "dev" # replace with fixed version outside of tests/examples
	url = "github:TyberiusPrime/anysnake2/main/1.15.5"


[nixpkgs]
	packages = []
	url = "github:NixOS/nixpkgs/master/21.05"


# the revision used by flake-util
# rev = "dc94135e31d5c90c40a00a6cbdf9330526e8153b" # optional
# url = "github:/DavHau/mach-nix"


[R] # R section is optional
#date="2021-10-27" # you get whatever packages were current that day.
	date="2022-05-10" # you get whatever packages were current that day.
# r_ecosystem_track_url= "github:TyberiusPrime/r_ecosystem_track" # optional
	packages = [
		"Rcpp",
		"stringi"
]
	url = "github:TyberiusPrime/nixR/main"


[R.additional_packages]
	"kedd_1.0.3" = '''{
      src = pkgs.fetchurl {
        sha256 = "38760abd8c8e8f69ad85ca7992803060acc44ce68358de1763bd2415fdf83c9f";
        url = "https://cran.r-project.org/src/contrib/Archive/kedd/kedd_1.0.3.tar.gz";
      };
    }
'''


[R.dependency_overrides]
	Rcpp = '''
old: old ++ ["R6"]
'''


[R.override_attrs]
	Rcpp = '''
old: {
postInstall = ''
  echo "Yes" >$out/library/Rcpp/override_in_place
'';
}
'''


[outside_nixpkgs]
	rev = "21.05"
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=54a06abec3273f42f9d86a36f184dbb3089cd9c9"


[poetry2nix]
	url = "github:nix-community/poetry2nix/master/8c25e871bba3f472e1569bbf6c0f52dcc34bf2a4"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"


# the revision used by flake-util
# rev = "7e5bf3925f6fbdfaf50a2a7ca0be2879c4261d19" # optional
# url = "github:/oxalica/rust-overlay"

[mach-nix]


