# fully featured anysnake2.toml example
[anysnake2]
	rev = "dev" # pre 2.0 - 2.0+ uses url2
	url = "github:TyberiusPrime/anysnake2_release_flakes" # pre 2.0 - 2.0+ uses url2
# We leverage nix flakes to run exactly that version.
	url2 = "dev"


[nixpkgs]
	packages = []
	url = "github:NixOS/nixpkgs/master/21.05"


# the revision used by flake-util
# rev = "dc94135e31d5c90c40a00a6cbdf9330526e8153b" # optional
# url = "github:/DavHau/mach-nix"


[R] # R section is optional
#date="2021-10-27" # you get whatever packages were current that day.
	date="2022-05-10" # you get whatever packages were current that day.
# r_ecosystem_track_url= "github:TyberiusPrime/r_ecosystem_track" # optional
	packages = [
		"Rcpp",
		"stringi"
]
	url = "github:TyberiusPrime/nixR/main"


[R.additional_packages]
	"kedd_1.0.3" = '''{
      src = pkgs.fetchurl {
        sha256 = "38760abd8c8e8f69ad85ca7992803060acc44ce68358de1763bd2415fdf83c9f";
        url = "https://cran.r-project.org/src/contrib/Archive/kedd/kedd_1.0.3.tar.gz";
      };
    }
'''


[R.dependency_overrides]
	Rcpp = '''
old: old ++ ["R6"]
'''


[R.override_attrs]
	Rcpp = '''
old: {
postInstall = ''
  echo "Yes" >$out/library/Rcpp/override_in_place
'';
}
'''


[dev_shell]
	inputs = []
	shell = "bash"


[outside_nixpkgs]
	rev = "21.05"
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=54a06abec3273f42f9d86a36f184dbb3089cd9c9"


[uv2nix]
	url = "github:adisbladis/uv2nix/master/0dfcb77f5bc5997ea61469119f0c1ac5ac9f5673"


[uv2nix_override_collection]
	url = "github:TyberiusPrime/uv2nix_hammer_overrides/main/e53075de5587a33b3b68a809ea3124b615ab260c"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"


# the revision used by flake-util
# rev = "7e5bf3925f6fbdfaf50a2a7ca0be2879c4261d19" # optional
# url = "github:/oxalica/rust-overlay"

[pyproject_build_systems]
	url = "github:pyproject-nix/build-system-pkgs/master/e1487e5cefda0c7990bdd2e660bee20971680e45"


