# pull a python package that has a complicated build process
# and has a flake.nix
# (since mach-nix doesn't do pep517 so far, and anyhow,
# for rust-packages you do need to nix-aware-fetch the cargo dependencies)
# )
# The flake exports a function mach-nix-build-python-package: nixpkgs: pythonpkgs: version
# see mbf_bam for an example

[anysnake2]
rev = "dev"

[outside_nixpkgs]
rev = "21.05" # the nixpgks version or github hash

[nixpkgs]
rev = "21.05" # the nixpgks version or github hash
packages = ["which"]


[python] # python section is optional
version="3.8" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)
ecosystem_date="2022-02-16" # you get whatever packages the solver would have produced on that day

[python.packages]
# just tell it to use 'useFlake' and define the flake below
mbf_bam = {method="useFlake"}#, flake_name="mbf_bam" is optional, defaults to package name.



[flakes.mbf_bam]
	url = "git+https://github.com/IMTMarburg/mbf_bam" #https://nixos.wiki/wiki/Flakes#Input_schema 
	rev = "c8745535b8c383457c789f8fc15f0b11d55502e6"

