# the absolute minimal anysnake2.toml example
[anysnake2]
url2 = "dev"


[nixpkgs]
rev = "24.05" # the nixpgks version or github hash
url = "github:NixOS/nixpkgs/master/24.05"


[rust]
version = "1.55.0"
url = "github:oxalica/rust-overlay/master/7df2ac544c203d21b63aac23bfaec7f9b919a733"

[outside_nixpkgs]
# the nixpkgs used to run singularity and nixfmt
rev = "21.05"
url = "github:NixOS/nixpkgs/master/24.05"

[ancient_poetry]
url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=204fc9fc15af8097ea0e40b80ef9b8d0691b832b"

[flake-util]
url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"