# basic anysnake2.toml example using python
[anysnake2]
	rev = "dev" # pre 2.0 - 2.0+ uses url2
	url = "github:TyberiusPrime/anysnake2_release_flakes" # pre 2.0 - 2.0+ uses url2
	url2 = "dev"


[nixpkgs]
	packages = ["which"]
	rev = "23.11" 
	url = "github:NixOS/nixpkgs/master/24.05"


[python] 
	ecosystem_date="2022-11-23" 
	preferWheels = true
	version="3.10" 


[python.packages]
	setuptools = ""# dppd_plotnine needs this


[python.packages.dppd]
	build_systems = ["setuptools"]
# could also be version="pypi:0.24"
	url = "https://files.pythonhosted.org/packages/4b/43/0d1b0135841e4f2b9a3208df24abef52dd368be166bb150369d2cd6c9bed/dppd-0.24.tar.gz"


[python.packages.dppd-plotnine]
	build_systems = ["setuptools"]
	override_attrs.postPatch = """''
	substituteInPlace setup.cfg \
		--replace-fail "pyscaffold>=3.1a0,<3.2a0" ""

	substituteInPlace setup.py --replace-fail "use_pyscaffold=True" ""
	# dppd_plotnine version resolution in 0.2 is borked
	substituteInPlace src/dppd_plotnine/__init__.py --replace-fail "__version__ = get_distribution(dist_name).version" "__version__ = '0.2'"
''"""
	version="0.2"


[dev_shell]
	inputs = []
	shell = "bash"


[outside_nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=204fc9fc15af8097ea0e40b80ef9b8d0691b832b"


[uv2nix]
	url = "github:adisbladis/uv2nix/master/31b316a8ee16d18c1ff4bbd9ee370cd289388f15"


[uv2nix_override_collection]
	url = "github:TyberiusPrime/uv2nix_hammer_overrides/main/e53075de5587a33b3b68a809ea3124b615ab260c"


[flake-util]
	url = "github:numtide/flake-utils/main/11707dc2f618dd54ca8739b309ec4fc024de578b"


[devshell]
	inputs = []
	shell = "bash"


[pyproject_build_systems]
	url = "github:pyproject-nix/build-system-pkgs/master/e1487e5cefda0c7990bdd2e660bee20971680e45"