# basic anysnake2.toml example
# package settings
[anysnake2]
	rev = "dev" # pre 2.0 - 2.0+ uses url2
	url = "github:TyberiusPrime/anysnake2" # pre 2.0 - 2.0+ uses url2
	url2 = "dev"
	use_binary=false # optional, default = true. Download anysnake2 binary instead of building from source (both via a flake)


[nixpkgs]
# the nixpkgs used inside the container
	packages = [ # use https://search.nixos.org/packages to search
		"evcxr",
]
	url = "github:NixOS/nixpkgs/master/24.05"


[python] # python section is optional
	ecosystem_date="2024-08-16" # you get whatever packages the solver would have produced on that day
	version="3.12" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)


[python.packages]
#pandas=""
	jupyter-black=""
	jupyterlab-code-formatter=""
# you can use version specifiers from https://www.python.org/dev/peps/pep-0440/#id53
	notebook=""


[R]
	date = "2024-05-10"
	packages = ['IRkernel']
	url = "github:TyberiusPrime/nixR/main/9c1b6cc8790dccddf583d45ad21ace80df5dbbe8"


[rust]
	url = "github:oxalica/rust-overlay/master/a71b1240e29f1ec68612ed5306c328086bed91f9"


[container.env]
	ANYSNAKE2="1"


# container settings
[container.volumes_rw]
	"." = "/project" # map the current folder to /project


[cmd.default]
	run = """
cd /project
jupyter notebook
"""


[cmd.shell]
	run = """fish
"""


[cmd.test_pre_post]
	post_run_outside = """
echo "post_run"
"""
	pre_run_outside = """
echo "pre_run"
"""
	run = """
echo "run"
"""
	while_run_outside ="""
while :
do
	# write pid to pre_run.txt
	echo "$BASHPID" > while_run.txt
	sleep 1;
done
"""


[dev_shell]
	inputs = []
	shell = "bash"


[outside_nixpkgs]
# the nixpkgs used to run singularity and nixfmt
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=b23dbf4c7beaa94bc3bfd2f766a953f405ae9afc"


[uv2nix]
	url = "github:adisbladis/uv2nix/master/31b316a8ee16d18c1ff4bbd9ee370cd289388f15"


[uv2nix_override_collection]
	url = "github:TyberiusPrime/uv2nix_hammer_overrides/main/e53075de5587a33b3b68a809ea3124b615ab260c"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"


[devshell]
	inputs = []
	shell = "bash"


[pyproject_build_systems]
	url = "github:pyproject-nix/build-system-pkgs/master/e1487e5cefda0c7990bdd2e660bee20971680e45"
