# basic anysnake2.toml example
[anysnake2]
	rev = "dev" # pre 2.0 - 2.0+ uses url2
	url = "github:TyberiusPrime/anysnake2_release_flakes" # pre 2.0 - 2.0+ uses url2
	url2 = "dev"


[nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


# and these are the other 'misc' clones that do not get turned into python packages
[clones.code]
	anysnake2_test_repo= "github:TyberiusPrime/_anysnake2_test_repo/main/97d57e17c1bd4a5f547fa1c1be57c2f0a1d2ec6f"


[clone_regexps]
	"@gh/([^/]+/[^/]+)"="github:$1/$2"


[python] # python section is optional
	ecosystem_date="2023-11-21" # you get whatever packages the solver would have produced on that day
	uv_lock_env = {"SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL"= "True"}
	version="3.11" # does not go down to 3.8.x. Thats implicit in the nixpkgs (for now)


[python.packages]
	mdataframe={ editable=true, url = "github:MarcoMernberger/mdataframe/master/93fd47ffba5f4a0aa59fd02a105ace33a705da71", build_systems = ["setuptools"]}
# this is how we now specify cloned python packages

	pypipegraph={ editable=true, url = "github:TyberiusPrime/pypipegraph/master/1430704960b069ba25de30210059dcaf374d4ae7", build_systems = ["setuptools"]}
	setuptools=""
	sklearn = {build_systems = ["setuptools"], override_attrs= {"SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL"= "\"True\""}}


[python.packages.pypipegraph2]
	editable=true
# yes, this is import from derivation.
	override_attrs.cargoDeps = """
	pkgs.rustPlatform.importCargoLock {
          lockFile = "${old.src}/Cargo.lock";
        }
"""
	override_attrs.nativeBuildInputs = '''old.nativeBuildInputs ++ [
		pkgs.rustPlatform.maturinBuildHook
		pkgs.rustPlatform.cargoSetupHook]'''
	url = "github:TyberiusPrime/pypipegraph2/main/264187207ffd4416074bb24d7b440ff5d838f199"


[rust]
	url = "github:oxalica/rust-overlay/master/d720bf3cebac38c2426d77ee2e59943012854cb8"
	version="1.70.0" # this is the default, but you can override it here


[dev_shell]
	inputs = []
	shell = "bash"


[outside_nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=204fc9fc15af8097ea0e40b80ef9b8d0691b832b"


[uv2nix]
	url = "github:adisbladis/uv2nix/master/31b316a8ee16d18c1ff4bbd9ee370cd289388f15"


[uv2nix_override_collection]
	url = "github:TyberiusPrime/uv2nix_hammer_overrides/main/e53075de5587a33b3b68a809ea3124b615ab260c"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"


[devshell]
	inputs = []
	shell = "bash"


[pyproject_build_systems]
	url = "github:pyproject-nix/build-system-pkgs/master/e1487e5cefda0c7990bdd2e660bee20971680e45"