[anysnake2]
	rev = "dev" # pre 2.0 - 2.0+ uses url2
	url = "github:TyberiusPrime/anysnake2_release_flakes" # pre 2.0 - 2.0+ uses url2
	url2="dev"


[nixpkgs]
	url = "github:nixos/nixpkgs/master/6efe194fbec6d156eedff4210476eb06bb844bc7"


[python]
	ecosystem_date="2022-11-23"
	preferWheels = true
	version="3.11"


[python.packages]
	black=""
	dppd = {}


#dppd = {poetry2nix.buildInputs = ["setuptools"]}
# 	dppd_plotnine = {version = "", editable=true, poetry2nix.buildInputs = ["setuptools", "pyscaffold"]}
# # that supplies 'hello'
# 	example-cli-python={ editable=true, url = "github:ojixzzz/example-cli-python/master/a981a9ea5468faa66fccc6c69c5d5807ef8115c4", poetry2nix.buildInputs = ["setuptools"]}
# 	hatchling=""
# 	lvr = { editable=true, url = "hg+https://hg.sr.ht/~bwe/lvr?rev=db6f0a3254fbd3939d6b6b8c6d1711e7129faba1",  poetry2nix.buildInputs = ["setuptools"]}
# 	pandas="1.5.1"
# 	polars={version = "pypi:0.20.31"}
# 	pyscaffold = "3.1"
# 	pytest=""
# #requests = {url = "https://files.pythonhosted.org/packages/63/70/2bf7780ad2d390a8d301ad0b550f1581eadbd9a20f896afe06353c2a2913/requests-2.32.3.tar.gz"}
# 	requests = { version = "pypi:2.32.2" }
# 	tomli=">1.2"


[dev_shell]
	inputs = []
	shell = "bash"


[outside_nixpkgs]
	url = "github:nixos/nixpkgs/master/6efe194fbec6d156eedff4210476eb06bb844bc7"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=b23dbf4c7beaa94bc3bfd2f766a953f405ae9afc"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"


[uv2nix]
	url = "github:adisbladis/uv2nix/master/cb4b2ba5c1cd24668c7c6d819f1c30b0a6960560"


[uv2nix_override_collection]
	url = "github:TyberiusPrime/uv2nix_hammer_overrides/main/6123143b7421406b90d6a945f88e36fc0c0228bc"


