# basic anysnake2.toml example using python
[anysnake2]
rev = "dev"

[outside_nixpkgs]
rev = "23.11" 

[nixpkgs]
rev = "23.11" 
packages = ["which"]


[python] 
version="3.10" 
ecosystem_date="2022-11-23" 
preferWheels = true

[clones.code]
# clones a repo to ./code, which you can then refer in python.
example-cli-python="file://./example-cli-python/"

[python.packages]
pandas="1.5.1"
black=""
tomli=">1.2"
hatchling=""
requests = {url = "https://files.pythonhosted.org/packages/63/70/2bf7780ad2d390a8d301ad0b550f1581eadbd9a20f896afe06353c2a2913/requests-2.32.3.tar.gz"}


