# basic anysnake2.toml example
# package settings
[anysnake2]
rev = "dev"

[outside_nixpkgs]
rev = "21.05" # the nixpgks version or github hash

[nixpkgs]
# the nixpkgs used inside the container
rev = "21.05" # the nixpgks version or github hash


[python] # python section is optional
version="3.8" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)
ecosystem_date="2021-08-16" # you get whatever packages the solver would have produced on that day

[clones.code]
example-cli-python="git+https://github.com/ojixzzz/example-cli-python"

[python.packages]
pandas="1.2"
# you can use version specifiers from https://www.python.org/dev/peps/pep-0440/#id53
example-cli-python="editable/code"
