[anysnake2]
	url="dev"


[nixpkgs]
	url = "github:nixos/nixpkgs/master/24.05"


[python]
	ecosystem_date="2022-11-23"
	preferWheels = true
	version="3.11"


[python.packages]
	black=""
	dppd = {poetry2nix.buildInputs = ["setuptools"]}
	dppd_plotnine = {version = "", editable=true, poetry2nix.buildInputs = ["setuptools", "pyscaffold"]}
	# that supplies 'hello'
	example-cli-python={ editable=true, url = "github:ojixzzz/example-cli-python/master/a981a9ea5468faa66fccc6c69c5d5807ef8115c4", poetry2nix.buildInputs = ["setuptools"]}
	hatchling=""
	lvr = { url = "hg+https://hg.sr.ht/~bwe/lvr?rev=db6f0a3254fbd3939d6b6b8c6d1711e7129faba1",  poetry2nix.buildInputs = ["setuptools"]}
	pandas="1.5.1"
	polars={version = "pypi:0.20.31"}
	pyscaffold = "3.1"
	pytest=""
#requests = {url = "https://files.pythonhosted.org/packages/63/70/2bf7780ad2d390a8d301ad0b550f1581eadbd9a20f896afe06353c2a2913/requests-2.32.3.tar.gz"}
	requests = { version = "pypi:2.32.2" }
	tomli=">1.2"


[outside_nixpkgs]
	url = "github:nixos/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=961eb418d95583dad83b35619b1973874b4c5bab"


#url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=68f1e759c557757e55d05027319d5c9751626fba"

[poetry2nix]
	preferWheels=true
	url = "github:nix-community/poetry2nix/master/5392004e2b350afda0dd5e92ccd53ab9b1261947"


#pytest=""


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"


