[anysnake2]
	rev = "dev" # pre 2.0 - 2.0+ uses url2
	url = "github:TyberiusPrime/anysnake2_release_flakes" # pre 2.0 - 2.0+ uses url2
	url2="dev"


[nixpkgs]
	packages =["which"]
	url = "github:nixos/nixpkgs/master/6efe194fbec6d156eedff4210476eb06bb844bc7"


[python]
	ecosystem_date="2022-11-23"
	preferWheels = true
	version="3.11"


[python.packages]
	black=""
	dppd = {build_systems = ["wheel"]}
	dppd_plotnine = {version = "", editable=true, build_systems = ["setuptools", "wheel"]}
# that supplies 'hello'
	example-cli-python={ editable=true, url = "github:TyberiusPrime/example-cli-python/main/6df1084dbd3dd2fc122068377ed041ea7d17adf5", build_systems = ["setuptools", "wheel"]}
	hatchling=""
	lvr = { editable=true, url = "hg+https://hg.sr.ht/~bwe/lvr?rev=db6f0a3254fbd3939d6b6b8c6d1711e7129faba1",  build_systems = ["setuptools"]}
	pandas="1.5.1"
	polars={version = "pypi:0.20.31"}
	pyscaffold = "3.1"
	pytest=""
#requests = {url = "https://files.pythonhosted.org/packages/63/70/2bf7780ad2d390a8d301ad0b550f1581eadbd9a20f896afe06353c2a2913/requests-2.32.3.tar.gz"}
	requests = { version = "pypi:2.32.2" }
	tomli=">1.2"
	wrapt = {build_systems = ["wheel"]}


[dev_shell]
	inputs = []
	shell = "bash"


[outside_nixpkgs]
	url = "github:nixos/nixpkgs/master/6efe194fbec6d156eedff4210476eb06bb844bc7"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=b23dbf4c7beaa94bc3bfd2f766a953f405ae9afc"


[uv2nix]
	url = "github:adisbladis/uv2nix/master/fd41fdec2fed599ba884bc2706c2263f01e2183c"


[uv2nix_override_collection]
	url = "github:TyberiusPrime/uv2nix_hammer_overrides/main/1e739d79d54799f3ad62d0c529073390ec8b8ddb"


[flake-util]
	url = "github:numtide/flake-utils/main/11707dc2f618dd54ca8739b309ec4fc024de578b"


[pyproject_build_systems]
	url = "github:pyproject-nix/build-system-pkgs/master/e1487e5cefda0c7990bdd2e660bee20971680e45"

