# basic anysnake2.toml example
# package settings
[anysnake2]
rev = "dev"

[outside_nixpkgs]
rev = "21.05" # the nixpgks version or github hash

[nixpkgs]
# the nixpkgs used inside the container
rev = "21.05" # the nixpgks version or github hash


[python] # python section is optional
version="3.8" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)
ecosystem_date="2021-08-16" # you get whatever packages the solver would have produced on that day

[clones.code]
example-cli-python="git+https://github.com/ojixzzz/example-cli-python"

[python.packages]
# you can use standard python requirements.txt version specification syntax
# i.e. version specifiers from https://www.python.org/dev/peps/pep-0440/#id53
pandas="1.2"
# you can refer to the repos you cloned

example-cli-python="editable/code"

# and you can fetch from github, git and mercurial (any nix fetcher actually, see
# https://nixos.org/manual/nixpkgs/stable/#chap-pkgs-fetchers)

#ugly syntax:
plotnine = {method = "fetchFromGitHub", owner = "has2k1", repo = "plotnine", rev = "6c82cdc20d6f81c96772da73fc07a672a0a0a6ef", hash = """
sha256-E5nR5xK+sqV3tlxnPDNE0TdTtYtPK47zgwzTG/KmXF0=
"""}
# pretty syntax
[python.packages.dppd] 
	method = "fetchFromGitHub"
	owner = "TyberiusPrime"
	repo = "dppd"
	rev = "b55ac32ef322a8edfc7fa1b6e4553f66da26a156"
hash = """
sha256-fyDDeJRbm9hMkefqiyxHazZut38rxgZVcyp+YpUglGI=
"""
	#hash = "sha256-fyDDeJRbm9hMkefqiyxHazZut38rxgZVcyp+YpUglGI="
# pandas="<1.0"
