# the absolute minimal anysnake2.toml example
[anysnake2]
	url = "dev" # replace with fixed version outside of tests/examples


# the nixpkgs used to run singularity and nixfmt


[nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


[flakes.sratoolkit]
	dir = "sratoolkit"
	packages = ["defaultPackage.x86_64-linux"]
	url = "github:IMTMarburg/flakes/main/356700f69497e12371aab6fe529d276893aaaf16"


[container]
	home="./no-home"


[outside_nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=54a06abec3273f42f9d86a36f184dbb3089cd9c9"


[poetry2nix]
	url = "github:nix-community/poetry2nix/master/cc0af1948e0887cd280496bd891fd40e52b40ff4"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"
