# the absolute minimal anysnake2.toml example
[anysnake2]
	rev = "dev" # pre 2.0 - 2.0+ uses url2
	url = "github:TyberiusPrime/anysnake2_release_flakes" # pre 2.0 - 2.0+ uses url2
	url2 = "dev" # replace with fixed version outside of tests/examples


# the nixpkgs used to run singularity and nixfmt


[nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


[flakes.sratoolkit]
	dir = "sratoolkit"
	packages = ["defaultPackage.x86_64-linux"]
	url = "github:IMTMarburg/flakes/main/356700f69497e12371aab6fe529d276893aaaf16"


[container]
	home="./no-home"


[dev_shell]
	inputs = []
	shell = "bash"


[outside_nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=204fc9fc15af8097ea0e40b80ef9b8d0691b832b"


[uv2nix]
	url = "github:adisbladis/uv2nix/master/fd41fdec2fed599ba884bc2706c2263f01e2183c"


[uv2nix_override_collection]
	url = "github:TyberiusPrime/uv2nix_hammer_overrides/main/1e739d79d54799f3ad62d0c529073390ec8b8ddb"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"


[devshell]
	inputs = []
	shell = "bash"


[pyproject_build_systems]
	url = "github:pyproject-nix/build-system-pkgs/master/e1487e5cefda0c7990bdd2e660bee20971680e45"