# basic anysnake2.toml example
# package settings
[anysnake2]
	rev = "dev" # pre 2.0 - 2.0+ uses url2
	url = "github:TyberiusPrime/anysnake2_release_flakes" # pre 2.0 - 2.0+ uses url2
	url2 = "dev"


[nixpkgs]
# the nixpkgs used inside the container
	packages = [
		"bash",
		"fish"]
	url = "github:NixOS/nixpkgs/master/24.05"


[python] # python section is optional
	ecosystem_date="2021-08-16" # you get whatever packages the solver would have produced on that day
	version="3.9" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)


[python.packages]
#cython = {build_systems = ["wheel"]}
#markupsafe = {build_systems = ["wheel"]}
# you can use version specifiers from https://www.python.org/dev/peps/pep-0440/#id53
	notebook=""
	pandas="1.2.0"
	pandocfilters = {build_systems = ["wheel"]}


#	psutil = {build_systems = ["wheel"]}


[rust]
	url = "github:oxalica/rust-overlay/master/d720bf3cebac38c2426d77ee2e59943012854cb8"
	version="1.55.0"


[container.env]
	ANYSNAKE2="1"


# container settings
[container.volumes_rw]
	"." = "/project" # map the current folder to /project


[cmd.default]
	run = """
cd /project
jupyter notebook
"""


[cmd.shell]
	run = """fish
"""


[cmd.test_pre_post]
	post_run_outside = """
echo "post_run"
"""
	pre_run_outside = """
echo "pre_run"
"""
	run = """
echo "run"
"""
	while_run_outside ="""
while :
do
	# write pid to pre_run.txt
	echo "$BASHPID" > while_run.txt
	sleep 1;
done
"""


[cmd.test_pre_post_single_line]
	post_run_inside = "echo 'posthello from inside'"
	post_run_outside = "echo 'posthello from outside'"
	pre_run_outside = "echo 'prehello from outside'"
	run = "echo 'hello from command'"


[dev_shell]
	inputs = []
	shell = "bash"


[outside_nixpkgs]
# the nixpkgs used to run singularity and nixfmt
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=b23dbf4c7beaa94bc3bfd2f766a953f405ae9afc"


[poetry2nix]
	url = "github:nix-community/poetry2nix/master/cc0af1948e0887cd280496bd891fd40e52b40ff4"


[uv2nix_override_collection]
	url = "github:TyberiusPrime/uv2nix_hammer_overrides/main/1e739d79d54799f3ad62d0c529073390ec8b8ddb"


[uv2nix]
	url = "github:adisbladis/uv2nix/master/fd41fdec2fed599ba884bc2706c2263f01e2183c"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"


[devshell]
	inputs = []
	shell = "bash"


[pyproject_build_systems]
	url = "github:pyproject-nix/build-system-pkgs/master/e1487e5cefda0c7990bdd2e660bee20971680e45"
