# pull a python package that has a complicated build process
# and has a flake.nix
# (since mach-nix doesn't do pep517 so far, and anyhow,
# for rust-packages you do need to nix-aware-fetch the cargo dependencies)
# )
# The flake exports a function mach-nix-build-python-package: nixpkgs: pythonpkgs: version
# see mbf_bam for an example

[anysnake2]
	url2 = "dev"


[nixpkgs]
	packages = ["which"]
	url = "github:NixOS/nixpkgs/master/24.05"


[python] # python section is optional
	ecosystem_date="2022-11-23" # you get whatever packages the solver would have produced on that day
	version="3.10" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)


[python.packages]
	dppd={version="pypi:0.26", poetry2nix.buildInputs = ["setuptools"] }
	scanpy={version="pypi:1.9.3", poetry2nix.buildInputs = ["flit-core", "setuptools-scm"]}
	session-info={version="pypi:1.0.0", poetry2nix.buildInputs = ["setuptools"]}


[cmd.python]
	run = """python
"""


[cmd.xxx]
	run="bash"


[outside_nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=54a06abec3273f42f9d86a36f184dbb3089cd9c9"


[poetry2nix]
	url = "github:nix-community/poetry2nix/master/884b66152b0c625b8220b570a31dc7acc36749a3"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"

