# pull a python package that has a complicated build process
# and has a flake.nix
# (since mach-nix doesn't do pep517 so far, and anyhow,
# for rust-packages you do need to nix-aware-fetch the cargo dependencies)
# )
# The flake exports a function mach-nix-build-python-package: nixpkgs: pythonpkgs: version
# see mbf_bam for an example

[anysnake2]
	rev = "dev" # pre 2.0 - 2.0+ uses url2
	url = "github:TyberiusPrime/anysnake2_release_flakes" # pre 2.0 - 2.0+ uses url2
	url2 = "dev"


[nixpkgs]
	packages = ["which"]
	url = "github:NixOS/nixpkgs/master/24.05"


[python] # python section is optional
	ecosystem_date="2022-11-23" # you get whatever packages the solver would have produced on that day
	version="3.10" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)


[python.packages]
	dppd={version="pypi:0.26", build_systems = ["setuptools"] }
	numba = {override_attrs = { buildInputs = "old.buildInputs ++ [ pkgs.tbb_2021_11.out ]" }}
	scanpy={version="pypi:1.9.3", build_systems = ["flit-core", "setuptools-scm"]}
	session-info={version="pypi:1.0.0", build_systems = ["setuptools"]}


[cmd.python]
	run = """python
"""


[cmd.xxx]
	run="bash"


[dev_shell]
	inputs = []
	shell = "bash"


[outside_nixpkgs]
	url = "github:NixOS/nixpkgs/master/24.05"


[ancient_poetry]
	url = "git+https://codeberg.org/TyberiusPrime/ancient-poetry.git?ref=main&rev=b23dbf4c7beaa94bc3bfd2f766a953f405ae9afc"


[uv2nix]
	url = "github:adisbladis/uv2nix/master/31b316a8ee16d18c1ff4bbd9ee370cd289388f15"


[uv2nix_override_collection]
	url = "github:TyberiusPrime/uv2nix_hammer_overrides/main/e53075de5587a33b3b68a809ea3124b615ab260c"


[flake-util]
	url = "github:numtide/flake-utils/main/b1d9ab70662946ef0850d488da1c9019f3a9752a"


[pyproject_build_systems]
	url = "github:pyproject-nix/build-system-pkgs/master/e1487e5cefda0c7990bdd2e660bee20971680e45"

