# pull a python package that has a complicated build process
# and has a flake.nix
# (since mach-nix doesn't do pep517 so far, and anyhow,
# for rust-packages you do need to nix-aware-fetch the cargo dependencies)
# )
# The flake exports a function mach-nix-build-python-package: nixpkgs: pythonpkgs: version
# see mbf_bam for an example

[anysnake2]
rev = "dev"

[outside_nixpkgs]

[nixpkgs]
packages = ["which"]


[python] # python section is optional
version="3.10" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)
ecosystem_date="2022-11-23" # you get whatever packages the solver would have produced on that day


[python.packages]
dppd={pypi="0.26", poetry2nix.buildInputs = ["setuptools"] }
scanpy={pypi="1.9.3", poetry2nix.buildInputs = ["flit-core", "setuptools-scm"]}
session-info={pypi="1.0.0", poetry2nix.buildInputs = ["setuptools"]}

[cmd.python]
run = """python
"""


[cmd.xxx]
run="bash"

[poetry2nix]

