# pull a python package that has a complicated build process
# and has a flake.nix
# (since mach-nix doesn't do pep517 so far, and anyhow,
# for rust-packages you do need to nix-aware-fetch the cargo dependencies)
# )
# The flake exports a function mach-nix-build-python-package: nixpkgs: pythonpkgs: version
# see mbf_bam for an example

[anysnake2]
rev = "dev"

[outside_nixpkgs]
rev = "23.05" # needs a newish poetry

[nixpkgs]
rev = "22.05" # the nixpgks version or github hash
packages = ["which"]


[python] # python section is optional
version="3.10" # does not go down to 3.8.x. That's implicit in the nixpkgs (for now)
ecosystem_date="2022-11-23" # you get whatever packages the solver would have produced on that day


[python.packages]
# just tell it to use 'useFlake' and define the flake below
dppd={pypi="0.26", "pypi_url_0.26" = "https://files.pythonhosted.org/packages/02/58/a56e8d1a3c246ec37120522b0093f0a4ff4d19998aa58996338bb3785235/dppd-0.26.tar.gz" } # version is auto detected
scanpy={pypi="1.9.3", "pypi_url_1.9.3" = "https://files.pythonhosted.org/packages/47/d5/7e580b69ac0279688c4739a508c8fa734998bfce984efba2d0755e4f0068/scanpy-1.9.3.tar.gz" } # version is auto detected


[cmd.xxx]
run="bash"

[cmd.python]
run = """python
"""

